#ifndef WORDLIST_HPP
#define WORDLIST_HPP

#include <string>
#include <vector>

// One mnemonic pair for a three-digit decimal index 000-999.
// `person` is the Person-list phrase; `object` is the Object-list phrase.
struct PersonObject
{
    std::string person;
    std::string object;
};

// Three PersonObject slots that together encode thirty bits of payload:
// nine bits (three octal digits, written as a 000-777 decimal) per slot,
// plus three Person/Object selector bits taken from which list each word used.
struct ThirtyBinaryDigitLoci
{
    PersonObject loci_list[3];
};

// Indexed by the three-digit decimal n from the CSV (000-999).
// A std::map<int, PersonObject> would give the same n -> pair lookup; a vector
// does too, as long as it stays ordered by n. std::map cannot look up the key
// from a value, so reverse (phrase -> n) maps are built at runtime in main.cpp
// with std::unordered_map, which is the right tool for that direction.
inline const std::vector<PersonObject> TripleDecimalDigitPeopleObjects = {
    /* 000 */ {"Suzy Snacktime (Kandyland)", "Sazae-san cat inside fruit (laranja, melancia)"},
    /* 001 */ {"Societte (Granblue Fantasy)", "Cesto de roupa suja"},
    /* 002 */ {"Susano (Smite)", "Sazón"},
    /* 003 */ {"Susamaru (Demon Slayer)", "Sismógrafo"},
    /* 004 */ {"Caesar Clown (One Piece)", "Seizer (inglês, tesoura, tesoura cirúrgica)"},
    /* 005 */ {"Cecil (O Show dos Looney Tunes)", "Seseli"},
    /* 006 */ {"Suzy Johnson (Phineas and Ferb)", "Sausage (inglês, linguiça)"},
    /* 007 */ {"Sasuke (Kirby)", "Suzy Kellems Invisible"},
    /* 008 */ {"Suzu Fujimi (Super Sonico)", "Seios da face"},
    /* 009 */ {"Saci-pererê (Sítio do Picapau Amarelo)", "Sassaby case (inglês)"},
    /* 010 */ {"Zetsu (Naruto)", "Stasis pod (inglês)"},
    /* 011 */ {"Ezio Auditore (Assassin's Creed)", "Estetoscópio"},
    /* 012 */ {"Sidon (Nintendo)", "Extintor"},
    /* 013 */ {"Saitama (One-Punch Man)", "Estoma"},
    /* 014 */ {"Estrela (Gumball)", "Esteira"},
    /* 015 */ {"Estelar (Jovens titãs)", "Estilingue"},
    /* 016 */ {"Stitch (Lilo&Stitch)", "Estojo escolar (bolsinha escolar)"},
    /* 017 */ {"Estica (Toy Story)", "Stock ticker (ticker, inglês)"},
    /* 018 */ {"Stefano (Madagáscar)", "Stove (fogão, inglês)"},
    /* 019 */ {"Zoidberg (Futurama)", "E-stop (botão de emergência, inglês)"},
    /* 020 */ {"Sinestro (DC Comics)", "Essência (perfume)"},
    /* 021 */ {"Sandy (Bob Esponja)", "Sandálias (beach shoe, chinelo)"},
    /* 022 */ {"Sininho (Tinker Bell)", "Usina nuclear (emission)"},
    /* 023 */ {"Snowmando (Fortnite)", "Cinema (projetor, claquete)"},
    /* 024 */ {"Snarf (ThunderCats)", "Cenoura (carrot)"},
    /* 025 */ {"Snailchan (Snailchan Adventure)", "Sinalizador"},
    /* 026 */ {"Sancho (Dragon Quest)", "Snowshoe (raquete de neve, inglês)"},
    /* 027 */ {"Sonic (Sonic)", "Sangue (bolsa de sangue, blood bag)"},
    /* 028 */ {"Sniff (Moomin TV show)", "Sanfona"},
    /* 029 */ {"Zeniba (Spirited Away)", "Sniper (rifle sniper)"},
    /* 030 */ {"Samus (Metroid)", "Semicírculo"},
    /* 031 */ {"Asmodeus (Helluva Boss)", "Semtex (granada)"},
    /* 032 */ {"Semente do Mal (He-Man)", "Semente"},
    /* 033 */ {"Zomom (Sonic)", "Samambaia"},
    /* 034 */ {"Smurfette (The Smurfs)", "Esmeril"},
    /* 035 */ {"Mr. Small (Roger Hargreaves)", "Sawmill (serraria, inglês)"},
    /* 036 */ {"Soma Schicksal (God Eater)", "Smasher (Potato Ricer, esmagador de batata)"},
    /* 037 */ {"Sam Eagle (The Muppet Show)", "Sumagre"},
    /* 038 */ {"Zamfir (Castlevania)", "Semáforo"},
    /* 039 */ {"Simba (Disney)", "Zimbel"},
    /* 040 */ {"Sahasrahla (Nintendo)", "Sorriso (rir)"},
    /* 041 */ {"Zora Ideale (Black Clover)", "Sardinha enlatada (atum)"},
    /* 042 */ {"Sorean (Xenoblade Chronicles)", "Seringa (vacina)"},
    /* 043 */ {"Surume (One Piece)", "Cerâmica"},
    /* 044 */ {"Saharah (Animal Crossing)", "Serra de arco (serrote, serra)"},
    /* 045 */ {"Sariel (Nanatsu no Taizai)", "Cereal"},
    /* 046 */ {"Sargento (Toy Story)", "Sea urchin (urching)"},
    /* 047 */ {"Sirigueijo (Seu Sirigueijo - Bob Esponja)", "Sarcófago"},
    /* 048 */ {"Surfista Prateado (Marvel)", "Cerveja (brahma, kaiser)"},
    /* 049 */ {"Sorbet (Final Fantasy)", "Sarape"},
    /* 050 */ {"Zilius Zox (DC Comics)", "Salsicha"},
    /* 051 */ {"Sultão (Aladdin)", "Solda (máscara de solda)"},
    /* 052 */ {"Slinky (Toy Story)", "Cilindro para massa"},
    /* 053 */ {"Celia Mae (Monstros S.A.)", "Salame (presunto, mortadela, head cheese)"},
    /* 054 */ {"Sailor Moon (Sailor Moon)", "Saleiro (Sal, salt)"},
    /* 055 */ {"Soleil (Fire Emblem)", "Celular"},
    /* 056 */ {"SlashMan.EXE (Mega Man)", "Slush (milkshake, inglês)"},
    /* 057 */ {"Sly Cooper (Sly Cooper)", "Silicone"},
    /* 058 */ {"Silver (Sonic)", "Salvia branca bastão"},
    /* 059 */ {"Slab (X-Men)", "Whistle buoy (boia de balizamento, nun buoy, inglês)"},
    /* 060 */ {"Seiji Sawamura (Midori Days)", "Sushi sasazushi"},
    /* 061 */ {"Sagittarius (Fairy Tail)", "Sushi temari mold"},
    /* 062 */ {"Seiji Aino (Love Tyrant)", "sushi narezushi"},
    /* 063 */ {"Seiji Amasawa (Whisper of the Heart)", "Sashimi de sapo"},
    /* 064 */ {"Sojiro Sakura (Persona 5 Royal)", "Sushi uramaki"},
    /* 065 */ {"Sage Yulyana (Bravely Default)", "Seashell (concha, inglês)"},
    /* 066 */ {"Seiji Shishikura (Boku no Hero)", "Sachê de chá"},
    /* 067 */ {"Zashiki (Onmyoji)", "Sushi gunkan (sushi)"},
    /* 068 */ {"Sage of Save (Wonder Boy)", "Sushi futomaki (suchi, sushi sashimi)"},
    /* 069 */ {"Zatch Bell (Zatch Bell)", "Sajjappa (pastel, empanada, risole, guioza)"},
    /* 070 */ {"Sykes (O Espanta Tubarões)", "Saxofone"},
    /* 071 */ {"Scott (Monstros S.A.)", "Skate"},
    /* 072 */ {"Saiken (Naruto)", "Soco-inglês"},
    /* 073 */ {"Escamoso (ThunderCats)", "Escumadeira"},
    /* 074 */ {"Escargoon (Kirby)", "Saca-rolhas"},
    /* 075 */ {"Esqueleto (He-Man)", "Saco de lixo (Lixo)"},
    /* 076 */ {"Esguicho (Os Incríveis)", "Squashy ball (puffer ball, inglês)"},
    /* 077 */ {"Sig Curtis (Fullmetal Alchemist)", "Squeaky chicken (frango de plástico, inglês)"},
    /* 078 */ {"Scoff (Donkey Kong 64)", "Escova"},
    /* 079 */ {"Scooby-doo (Scooby-doo)", "Ice cap (inglês)"},
    /* 080 */ {"Zofis (Zatch Bell)", "Safe sex (camisinha, preservativo, inglês)"},
    /* 081 */ {"Soviete Supremo (DC Comics)", "Softbox"},
    /* 082 */ {"Ace Ventura (Ace Ventura animated)", "Sea fan (Gorgonia ventalina, inglês)"},
    /* 083 */ {"Sofia Murray (Vampirella)", "Sifão multiuso (Sifão, siphon)"},
    /* 084 */ {"Safira Estrela (Liga da Justiça)", "Esfregão"},
    /* 085 */ {"Oswaldo (Cartoon Network)", "Swivel (inglês)"},
    /* 086 */ {"Savage Dragon (Image Comics)", "Ceviche"},
    /* 087 */ {"Suffix (Asterix & Obelix)", "Esfigmomanômetro (medidor de pressão)"},
    /* 088 */ {"Sofia Valmet (Jormungand)", "Safe vault wheel (inglês)"},
    /* 089 */ {"Sofia Bulga (Tsuki ga Michibiku Isekai Douchuu)", "Safe box (cofre)"},
    /* 090 */ {"Space Hero (Boku no Hero)", "Spa stones (pedra, inglês)"},
    /* 091 */ {"Espeto (Toy Story)", "Espetinho (kabob)"},
    /* 092 */ {"Espantalho (DC Comics)", "Espanador"},
    /* 093 */ {"Spamley (Detona Ralph)", "Submetralhadora (metralhadora)"},
    /* 094 */ {"Swiper (Dora the Explorer)", "Sabre de luz"},
    /* 095 */ {"Cebolinha (Turma da Mônica)", "Cebola"},
    /* 096 */ {"Special Week (Uma Musume)", "Speech (pódio, inglês)"},
    /* 097 */ {"Spike (He-Man)", "Sabugo de milho (milho)"},
    /* 098 */ {"SBF Bear (Roblox BEAR)", "Sabava jackfruit chips"},
    /* 099 */ {"Zapp Brannigan (Futurama)", "Sabão em pó"},
    /* 100 */ {"Tsuyu Asui (Boku no Hero)", "Taças (engradado para taças)"},
    /* 101 */ {"Yatsude (Yu Yu Hakusho)", "Testículos"},
    /* 102 */ {"Docinho (Meninas Superpoderosas)", "Desentupidor"},
    /* 103 */ {"Daisy Mae (Animal Crossing)", "Taoism (coin-sword, espada, katana)"},
    /* 104 */ {"Tiz Arrior (Bravely Default)", "Taser"},
    /* 105 */ {"Diesel (One Piece)", "Dossel (mosquiteiro, inglês)"},
    /* 106 */ {"Daisy Jo (My Little Pony: Friendship Is Magic)", "Disjuntor"},
    /* 107 */ {"Duas-Caras (DC Comics)", "Otoscópio"},
    /* 108 */ {"Desafiador (Marvel)", "Adesivo Forte Coluna de Espuma"},
    /* 109 */ {"Dois berto (double dan - WiFi Ralph)", "Toss Up DGS Ninja"},
    /* 110 */ {"Tudo Sabe (WiFi Ralph)", "Thaddeus Wolfe 2022-05"},
    /* 111 */ {"Dedede (Nintendo)", "Eight-Eyed Teratorn Tie (Elysium, máscara da peste bubônica)"},
    /* 112 */ {"Detona Ralph (Detona Ralph)", "Tutankhamon (A máscara de Tutankhamon)"},
    /* 113 */ {"Tatami (Boku no Hero)", "Tatami (capacho, tapete)"},
    /* 114 */ {"Totoro (My Neighbor Totoro)", "Detergente"},
    /* 115 */ {"Tweedledee (Alice no país das maravilhas)", "Dedal"},
    /* 116 */ {"Deathwish (DC Comics)", "Detacher with Lanyard"},
    /* 117 */ {"Diddy Kong (Donkey Kong)", "Detector de metais"},
    /* 118 */ {"Deadfire (Fortnite)", "Tadafa Hump Retro Motorcycle Seat"},
    /* 119 */ {"Edith Up (Rayman Origins)", "Audiotape (fita cassete, inglês)"},
    /* 120 */ {"Thanos (Marvel)", "Dinossauro (esqueleto de dinossauro)"},
    /* 121 */ {"Toni Trombada (Nintendo)", "TNT"},
    /* 122 */ {"Tanya Winters (Saints Row)", "Athenian (parthenon)"},
    /* 123 */ {"Edna Moda (Os incríveis)", "Dinamômetro"},
    /* 124 */ {"Tina Russo (O Show dos Looney Tunes)", "Atoner module (inglês)"},
    /* 125 */ {"Donald Moderate (One Piece)", "Túnel"},
    /* 126 */ {"Tiansheng (Animal Crossing)", "Tangerina"},
    /* 127 */ {"Tiny Kong (Donkey Kong)", "Túnica"},
    /* 128 */ {"Danny Phantom (Danny Phantom)", "Wooden fife (Fife wooden, flauta)"},
    /* 129 */ {"Tawna Bandicoot (Crash Bandicoot)", "Wooden box (Inlaid box, caixa, caixa de papelão, baú)"},
    /* 130 */ {"Atmos (DC Comics)", "Tums (tic tac)"},
    /* 131 */ {"Tamatoa (Moana)", "Tomada"},
    /* 132 */ {"Diamante (Ben 10)", "Dominó"},
    /* 133 */ {"Tom Mate (Carros)", "Tim maia (peruca, black power)"},
    /* 134 */ {"Tomar Re (DC Comics)", "Dimer"},
    /* 135 */ {"Dim Long (Lilo & Stitch)", "Tamale"},
    /* 136 */ {"Tom Jumbo-Grumbo (BoJack Horseman)", "Damage meter (Crossout)"},
    /* 137 */ {"Tamago (One Piece)", "Tomacco (tomate, dos simpsons)"},
    /* 138 */ {"Doomfist (Overwatch)", "TMV (Mosaico do Tabaco)"},
    /* 139 */ {"Dumbo (Dumbo)", "Tampa de bueiro"},
    /* 140 */ {"Tristeza (Divertida Mente)", "Torre de sinal (sonda de perfuração)"},
    /* 141 */ {"Terri e Terry Perry (Monstros S.A.)", "Dardo"},
    /* 142 */ {"Tornado Vermelho (DC Comics)", "Triângulo instrumental"},
    /* 143 */ {"Tromba (Dona Tromba)", "Termômetro"},
    /* 144 */ {"Derriere (Nanatsu no Taizai)", "Tarara para limpar cereais"},
    /* 145 */ {"Trollex (Trolls)", "Treliça"},
    /* 146 */ {"Turgid the Vile (World of Warcraft)", "Tarraxa (de violão, de cano)"},
    /* 147 */ {"Dragão (Shrek)", "Target (alvo, inglês)"},
    /* 148 */ {"Darwin Watterson (O incrível mundo de Gumball)", "Travesseiro"},
    /* 149 */ {"Turbo (Detona Ralph)", "Torre de Pisa"},
    /* 150 */ {"Tails (Sonic)", "Telescópio"},
    /* 151 */ {"Waddle Dee (Kirby)", "Delta (asa delta)"},
    /* 152 */ {"Adeleine (Nintendo)", "Delineador (liner)"},
    /* 153 */ {"Dalmatian (One Piece)", "Tálamo (cérebro)"},
    /* 154 */ {"Tylor Tuskmon (Monstros S.A.)", "Toalha de rosto (toalha)"},
    /* 155 */ {"Talia Al Ghul (DC Comics)", "Idle Wheel (engrenagem, cogwheel, inglês)"},
    /* 156 */ {"Deluge (X-men)", "Telha de chapa (telha, laje)"},
    /* 157 */ {"Woodlegs (Don't Starve)", "Talco"},
    /* 158 */ {"Edel Frost (Grand Chase)", "Telefone"},
    /* 159 */ {"Odalia Blight (Casa da Coruja)", "Tela de projeção"},
    /* 160 */ {"DJ Suki (Trolls)", "Dish stand (escorredor de pratos, Alpife)"},
    /* 161 */ {"Digit (Cyberchase)", "Woodshed (inglês)"},
    /* 162 */ {"Toshinori (Boku no Hero)", "Tachinha (tacha)"},
    /* 163 */ {"Eto Yoshimura", "Taj Mahal"},
    /* 164 */ {"Itejiro (Boku no Hero)", "Dishware (prato, inglês)"},
    /* 165 */ {"Tijolinho (TV Aparecida)", "Tijolo"},
    /* 166 */ {"Toshi Yoshida (American Dad)", "Dishwasher (lava louças, inglês)"},
    /* 167 */ {"Dōshu Goetsu (Naruto)", "Dish cover (cloche, inglês)"},
    /* 168 */ {"Déjà Vu (Skylanders)", "Déjà Vu by David C. Roy"},
    /* 169 */ {"Dash Bowman (Star Fox)", "Dish petri (petri dish)"},
    /* 170 */ {"Dexter (Dexter's Laboratory)", "Taco de sinuca"},
    /* 171 */ {"Tuk Tuk (Raya e o Último Dragão)", "Etiqueta (rótulo)"},
    /* 172 */ {"Tecna (Clube das Winx)", "Daikon"},
    /* 173 */ {"Dagama (One Piece)", "Taco Mexicano (taco, kebab)"},
    /* 174 */ {"Tigrão (Ursinho Pooh)", "Tacker (grampeador, inglês)"},
    /* 175 */ {"Tikal (Sonic)", "Teclado"},
    /* 176 */ {"Taiki Shuttle (Uma Musume)", "Dockage tester (inglês)"},
    /* 177 */ {"Duke Caboom (Toy Story)", "Taco de golfe"},
    /* 178 */ {"Dick Vigarista (Corrida Maluca)", "Adaga do wolverine"},
    /* 179 */ {"Togepi (Pokémon)", "Taco de baseball"},
    /* 180 */ {"Devastadora (DC comics)", "Difusor"},
    /* 181 */ {"Te Fiti (Moana)", "DVD (CD)"},
    /* 182 */ {"Daphne Blake (Scooby-doo)", "Tafone"},
    /* 183 */ {"Dave Miller (Dayshift at Freddy's)", "TAVI medtronic (TAVI valve)"},
    /* 184 */ {"Toy Freddy (FNAF)", "Difra (Dispositivo Fototerápico para Rinite Alérgica)"},
    /* 185 */ {"Etevaldo (Castelo Rá-Tim-Bum)", "Teflon PFTE"},
    /* 186 */ {"Davy Jones (Pirates of the Caribbean)", "Defa charging station (Defa power)"},
    /* 187 */ {"Daifugo (One Piece)", "Tufa gardens lake (tufa calcária)"},
    /* 188 */ {"Devi Fudo (Kiratto Pri☆Chan)", "Divã veludo (sofá)"},
    /* 189 */ {"Diva Plavalaguna (Fifth Element)", "Tevo black widow (impressora 3D)"},
    /* 190 */ {"Tobias Wilson (O Incrível Mundo de Gumball)", "Diapasão"},
    /* 191 */ {"Tap Tap The Chiseler (Underdog)", "Adaptador"},
    /* 192 */ {"T-Bone (Toy Story)", "Tubo de ensaio"},
    /* 193 */ {"White Bomberman (Bomberman)", "Auto Bomba Tanque (caminhão de bombeiros)"},
    /* 194 */ {"Tubarão-Rei (DC Comics)", "wood board (tábua)"},
    /* 195 */ {"Doppler (Mega Man)", "Tapa olho"},
    /* 196 */ {"TiPche (Eduardo Fiore)", "White beech mushroom (cogumelo, nameko, inglês)"},
    /* 197 */ {"Tabak (Jonny Quest)", "Tábua de corte (tábua, wood board)"},
    /* 198 */ {"White Peafowl (Kemono Friends)", "Tubo de formatura"},
    /* 199 */ {"Tao Pai Pai (dragon ball)", "Tábua de passar roupa"},
    /* 200 */ {"Nasus (League of Legends)", "Enzo Scatragli sculpture"},
    /* 201 */ {"Anais Watterson (Gumball)", "Inseticida"},
    /* 202 */ {"Nice Nature (Uma Musume)", "Incenso"},
    /* 203 */ {"Inazuma (One Piece)", "Enzima (amilase)"},
    /* 204 */ {"Inasa Yoarashi (Boku no Hero)", "Ionizer (ionizador)"},
    /* 205 */ {"Nozel (Black Clover)", "Nacela"},
    /* 206 */ {"Nezu Jinpachi (Kurenai no Homura Sanada Ninpou Chou)", "Noisy joint wishbone"},
    /* 207 */ {"Insectossauro (Monstros vs. Alienígenas)", "Enciclopédia (livro, dicionário)"},
    /* 208 */ {"Anzu Futaba (The Idolmaster)", "Anne-sophie Gilloen Naturliebe"},
    /* 209 */ {"Ana Spanakopita (BoJack Horseman)", "Unzip Toy"},
    /* 210 */ {"Natsu (Fairy Tail)", "Endoscope"},
    /* 211 */ {"Onda Térmica (DC Comics)", "Andador"},
    /* 212 */ {"Anthony (Saints Row)", "Antena parabólica"},
    /* 213 */ {"Anti Monitor (DC Comics)", "Nota Musical"},
    /* 214 */ {"N. Trance (Crash Bandicoot)", "Interrogação"},
    /* 215 */ {"NeedleMan.EXE (Mega Man)", "Nutella"},
    /* 216 */ {"Enta Jinnai (Sarazanmai)", "Nitsha neck pillow (travesseiro pescoço, neck pillow)"},
    /* 217 */ {"Indigo (One Piece)", "Antique (inglês)"},
    /* 218 */ {"Annetta Fish (Rayman Origins)", "Endívia"},
    /* 219 */ {"Winnie-the-Pooh (Winnie-the-Pooh)", "Notebook"},
    /* 220 */ {"Ananas (Monsieur Ananas - Téléfrancais!)", "Ananás (abacaxi)"},
    /* 221 */ {"Nina Tucker (Fullmetal Alchemist)", "Anoint (conta gotas, inglês)"},
    /* 222 */ {"Nina Einstein (Code Geass)", "Unknown profile picture (inglês)"},
    /* 223 */ {"Nanami Kuon (Ya Boy Kongming!)", "Anonymous (máscara anonymous)"},
    /* 224 */ {"Neinhart (Fairy Tail)", "Onion ring"},
    /* 225 */ {"Nina Williams (Tekken)", "No nail (cola selante na pistola aplicadora)"},
    /* 226 */ {"Nana Shimura (Boku no Hero)", "Nunchakus"},
    /* 227 */ {"Nangi (One Piece)", "Onion cutter (onion chopper)"},
    /* 228 */ {"Ninfa (Hora de Aventura)", "Nenúfar (lótus)"},
    /* 229 */ {"Nani Pelekai (Lilo & Stitch)", "Nun buoy (whistle buoy, boia de balizamento, inglês)"},
    /* 230 */ {"Naomasa (Boku no Hero)", "Namsan heart"},
    /* 231 */ {"Onomatopeia (DC Comics)", "Nômade totem"},
    /* 232 */ {"Ino Yamanaka (Naruto)", "Anêmona-do-mar"},
    /* 233 */ {"Naomi McDuffie (DC Comics)", "Anemômetro"},
    /* 234 */ {"Namur (One Piece)", "Número"},
    /* 235 */ {"Animal (muppets)", "NuMe Lustrum (cacetete, NuMe Classic Curling Wand Pearl)"},
    /* 236 */ {"Nao Miyoshi (Girl Friend Beta)", "Naomi Schindler Bronze 1976"},
    /* 237 */ {"Inmaki (Yu Yu Hakusho)", "Nameko (white beech mushroom, cogumelo)"},
    /* 238 */ {"Nymph (Contra Returns)", "NuMu Federico Herrero (Nuevo Museo de Arte Contemporáneo)"},
    /* 239 */ {"NumberMan.EXE (Mega Man)", "Namibia returned object"},
    /* 240 */ {"Naru Osaka (Sailor Moon)", "Nariz"},
    /* 241 */ {"Naruto (Naruto)", "Aneróide de coluna"},
    /* 242 */ {"Narancia (Jojo no Kimyou na Bouken)", "Neurônio (nervo)"},
    /* 243 */ {"Narmaya (Granblue Fantasy)", "Normal Distribution Curve"},
    /* 244 */ {"Anhur (Smite)", "Ni-hard"},
    /* 245 */ {"Gnarly Eddy (Splatoon)", "Enrolador de fio"},
    /* 246 */ {"Inuarashi (One Piece)", "Nourisher (nectar nourisher, nectar feeder, inglês)"},
    /* 247 */ {"Anarquia (DC Comics)", "Narguilé"},
    /* 248 */ {"Nervasahno (Commander Nervasahno - Cosmic Wonders)", "Nerf belt"},
    /* 249 */ {"Nera Briscoletti (Dragon Quest)", "Anaerobic box"},
    /* 250 */ {"Nelson (Simpsons)", "Nils Völker Sculpture (Bola que aumenta e diminui nome)"},
    /* 251 */ {"Neil deBuck Weasel (Ice Age)", "Inlet chamber (boca de lobo, bueiro)"},
    /* 252 */ {"Noel Niihashi (Bleach)", "Nylon"},
    /* 253 */ {"Neal McBeal (BoJack Horseman)", "Nolma keybox"},
    /* 254 */ {"Noelle Holiday (Deltarune)", "Nailer (furadeira)"},
    /* 255 */ {"Nelliel (Bleach)", "Neil Lawson Sterling"},
    /* 256 */ {"Neil Josten (All for the Game)", "Unleasher (Lightbreak Unleasher, escudo, inglês)"},
    /* 257 */ {"Unluckies (One Piece)", "Analog tv remote (controle remoto, inglês)"},
    /* 258 */ {"Nullifier (GI Joe)", "Nullifier (Dota 2)"},
    /* 259 */ {"Nullpudding (Fairy Tail)", "Anel do poder (Senhor dos Anéis)"},
    /* 260 */ {"Nochizawa (Sword Art Online)", "Nachos (nacho)"},
    /* 261 */ {"Wan Shi Tong (Avatar: A Lenda de Aang)", "Enxada"},
    /* 262 */ {"Nojinho (Divertida Mente)", "Engine (REV UP Remanufactured Engine, gerador, esmeril)"},
    /* 263 */ {"Anji Mito (Guilty Gear)", "Enxó de madeira"},
    /* 264 */ {"Nashiro (Tokyo Ghoul)", "Nigerian Mancala Game"},
    /* 265 */ {"Wynnchel (Detona Ralph)", "Angel wings ( asa, wing, wings, inglês)"},
    /* 266 */ {"No. 66 (Soldier No. 66- Nichijou)", "Inchi shell (Sacha inchi shell)"},
    /* 267 */ {"Nishiki (Tokyo Ghoul)", "Enxaguador de vidro"},
    /* 268 */ {"Anchovy (Animal Crossing)", "Anchova (salmão, peixe)"},
    /* 269 */ {"Angie Peterson (Commissioner Gordon)", "Incha bath scrubber"},
    /* 270 */ {"Nix (Zooba)", "Onyx"},
    /* 271 */ {"Nocturne (Danny Phantom)", "Negatoscópio"},
    /* 272 */ {"Enko Onikuma (Naruto)", "NIKON lente (luneta, ampufi monocular)"},
    /* 273 */ {"Nagamasa (Boku no Hero)", "Enigma máquina (Datilográfica, máquina datilográfica)"},
    /* 274 */ {"Unicórnio (Divertida Mente)", "Âncora"},
    /* 275 */ {"Knuckles (Sonic)", "Inkle loom"},
    /* 276 */ {"Yangchen (Avatar: A Lenda de Aang)", "Encaixe (torre de Hanói, Hanói, torre de encaixe)"},
    /* 277 */ {"Nagao Kuu (Sengoku†Koihime)", "Inca god sun disk"},
    /* 278 */ {"Negev (Girls Frontline)", "Inca fertility vessel"},
    /* 279 */ {"Innkeeper (Castlevania)", "Knee cap (joelheira, inglês)"},
    /* 280 */ {"No-Face (Spirited Away)", "Nave espacial (shuttle, cápsula espacial)"},
    /* 281 */ {"Nephtis (Zone of The Enders)", "Naftalina"},
    /* 282 */ {"Nevana (Detona Ralph)", "Infinito"},
    /* 283 */ {"Novu Moru (B-Daman Crossfire)", "Nuvem"},
    /* 284 */ {"nefarious (Ratchet & Clank)", "Inversor"},
    /* 285 */ {"Niva Lada (Hitsugi no Chaika: Avenging Battle)", "Novelo de lã (bola de lã)"},
    /* 286 */ {"Inveja (Fullmetal Alchemist)", "Navajo dream catcher (caçador de sonhos)"},
    /* 287 */ {"Navi-kun (Pop'n Music)", "In vacuo (Evaporador rotativos)"},
    /* 288 */ {"Neefa Feefa (Pontoffel Pock and His Magic Piano)", "Kniphofia"},
    /* 289 */ {"Nevo Binklemeyer (Ratchet & Clank)", "New vip (colchão)"},
    /* 290 */ {"Ann Possible (Kim Possible)", "Ônibus"},
    /* 291 */ {"Nabbit (Mario)", "Knapweed"},
    /* 292 */ {"Nobunaga Hazama (Hunter x Hunter)", "Nubbin Pink Ivory"},
    /* 293 */ {"Inaba Miu (Planet With)", "Naboom (árvore, bonsai)"},
    /* 294 */ {"Annaberg (Shakugan no Shana)", "Napron"},
    /* 295 */ {"Nibbler (Futurama)", "Nebulizador irrigação"},
    /* 296 */ {"Nobu Yoshioka (Marvel)", "NUBOCHA (sorvete em bolas)"},
    /* 297 */ {"Inaba Gou (Tenka Hyakken)", "Winnebago (carro)"},
    /* 298 */ {"Nabiva the Druid (Toyhouse)", "Nipavo Chrome Razor Stand"},
    /* 299 */ {"Napapa (Dragon Ball)", "Nubia pendant (Hathor-Headed Crystal Pendant)"},
    /* 300 */ {"Mousesack (The Witcher)", "Mesa de som"},
    /* 301 */ {"Mística (X-men)", "Mastro (bandeira)"},
    /* 302 */ {"Mason (Fullmetal Alchemist)", "Maçaneta (fechadura)"},
    /* 303 */ {"Mezmer (My Life as a Teenage Robot)", "Omasum (inglês)"},
    /* 304 */ {"Maes Hughes (Fullmetal Alchemist)", "Muçarela"},
    /* 305 */ {"Mussels (Fish Hooks)", "Muzzle (focinheira, inglês)"},
    /* 306 */ {"Mezo Shoji (Boku no Hero)", "Mesa de jardim (mesa)"},
    /* 307 */ {"O Máskara (O Máskara)", "Máscara de Jim Carrey"},
    /* 308 */ {"Misfire (Transformers)", "Maçã verde"},
    /* 309 */ {"Masapi (Aiseki Mogol Girl)", "Mousepad"},
    /* 310 */ {"Medusa (Hércules)", "Motosserra"},
    /* 311 */ {"Matatabi (Naruto)", "Medidor de corrente (amperímetro)"},
    /* 312 */ {"Midna (Nintendo)", "Mitten (luva, luva de box, inglês)"},
    /* 313 */ {"Matt Major (PaRappa the Rapper)", "Modem (roteador)"},
    /* 314 */ {"Madruga (Seu Madruga)", "Moedor"},
    /* 315 */ {"Muttley (Corrida Maluca)", "Medalha"},
    /* 316 */ {"Meddy.EXE (Mega Man)", "Mouthwasher (enxaguante bucal)"},
    /* 317 */ {"Medaka (One Piece)", "Medical microscope (microscópio, inglês)"},
    /* 318 */ {"Medivh (World of Warcraft)", "Umidificador"},
    /* 319 */ {"Meat Boy (Super Meat Boy)", "Matapi sintético"},
    /* 320 */ {"Homenzinho verde (Toy Story)", "Monociclo"},
    /* 321 */ {"Manda-chuva (Manda-chuva)", "Monado (Xenoblade Chronicles)"},
    /* 322 */ {"Minion Stuart (Minions)", "Minoan marble conical rhyton"},
    /* 323 */ {"Minnie Mouse (Disney)", "Manômetro de coluna"},
    /* 324 */ {"Manhattan (Doutor Manhattan)", "Menorá (castiçal, candelabro)"},
    /* 325 */ {"Manuel Orejuela (Saints Row)", "Manilha"},
    /* 326 */ {"Mina Ashido (Boku no Hero)", "Mangedoura"},
    /* 327 */ {"Minguado (A Mansão Foster)", "Mangueira"},
    /* 328 */ {"Manivela (Robôs)", "Moinho de vento (moinho)"},
    /* 329 */ {"Mounblutain (One Piece)", "Manopla do Thanos"},
    /* 330 */ {"Mimzy (Hazbin Hotel)", "Mimosa"},
    /* 331 */ {"Homem de Lata (O Mágico de Oz)", "Mamadeira (biberon, feeder bottle)"},
    /* 332 */ {"Mammon (Hazbin Hotel)", "Mamona"},
    /* 333 */ {"Mimimi (Platinum End)", "M&M Mcflurry"},
    /* 334 */ {"Homem-aranha (Marvel)", "Memória SSD"},
    /* 335 */ {"Mimi Lucien (PlayKids)", "Mamilo (peito, bosom)"},
    /* 336 */ {"Momiji (Blue Archive)", "M&M chocolate dispenser (gumball machine, inglês)"},
    /* 337 */ {"Homem Calendário (DC Comics)", "Mimeográfo"},
    /* 338 */ {"Homem-Fera (He-Man)", "M&M vending machine (automática de vendas, máquina, inglês)"},
    /* 339 */ {"Mumbies (Kirby)", "M&M pretzel (inglês)"},
    /* 340 */ {"Amy Rose (Sonic)", "Morse (máquina de código morse, telégrafo)"},
    /* 341 */ {"Morty (Rick and Morty)", "Mordaça (lockjaw)"},
    /* 342 */ {"Marny (Katamari)", "Morango"},
    /* 343 */ {"Muhammad Avdol (Jojo no Kimyou na Bouken)", "Marmitex"},
    /* 344 */ {"Mahiru (Princess Connect! Re:Dive)", "Mirror (espelho, vidro, inglês)"},
    /* 345 */ {"Emerl (Sonic)", "Mural (lousa de avisos)"},
    /* 346 */ {"Marge Simpson (Simpsons)", "Marcha de carro"},
    /* 347 */ {"Margarida (Mickey Mouse)", "Mergulho (máscara de mergulho, snorkel)"},
    /* 348 */ {"Marvin (O Show dos Looney Tunes)", "MIRV"},
    /* 349 */ {"Maury Beverly (Big Mouth)", "Marupá (madeira, tronco de árvore)"},
    /* 350 */ {"Melzargard (One-Punch Man)", "Amilase (enzima)"},
    /* 351 */ {"Multiplex (DC Comics)", "Muleta"},
    /* 352 */ {"Melancolia (Divertida Mente)", "Melancia"},
    /* 353 */ {"Melman (Madagascar)", "Molho de mostarda (mostarda)"},
    /* 354 */ {"Mulher-Maravilha (Liga da justiça)", "Mala de rodinhas (mala, mala de viagem)"},
    /* 355 */ {"Millie Larsen (South Park)", "Molho de alho"},
    /* 356 */ {"Milly Ashford (Code Geass)", "Mulch (adubo, inglês)"},
    /* 357 */ {"Milky (One Piece)", "Milho em conserva (milho)"},
    /* 358 */ {"Malévola (Disney)", "Mala de viagem (mala, mala de rodinhas)"},
    /* 359 */ {"Melba (Animal Crossing)", "Molho de pimenta (pimenta)"},
    /* 360 */ {"Miche Zacharius (Attack on Titan)", "Meshes (inglês)"},
    /* 361 */ {"Majitani (hunter x hunter)", "Machado"},
    /* 362 */ {"Majin Boo (dragon ball)", "Motion (inertia, Newton's craddle, inglês)"},
    /* 363 */ {"Machamp (Pokémon)", "Mitchum (Roll-on)"},
    /* 364 */ {"Masher (Kirby)", "Majora (The Legend of Zelda)"},
    /* 365 */ {"Michel Yamada (Captain Tsubasa)", "Mochila a jato (fortnite)"},
    /* 366 */ {"Mojo Jojo (Powerpuff Girls)", "Mesh Chewy (harness, Load Up Dog Harness)"},
    /* 367 */ {"Magic Man (Mega Man)", "Magic wand"},
    /* 368 */ {"Machvise (One Piece)", "Mojave megaphone"},
    /* 369 */ {"Mishap (Dumb Ways to Die)", "MATCHBOX skybuster lançador"},
    /* 370 */ {"Mike Wazowski (Monstros SA)", "Mixer de mão"},
    /* 371 */ {"Mikita (One Piece)", "Mictório"},
    /* 372 */ {"Magneto (X-men)", "Magnet (ímã)"},
    /* 373 */ {"Mickey Mouse (Disney)", "Magma (lava)"},
    /* 374 */ {"Makarov (Fairy Tail)", "Macarrão (espaguete, yakisoba)"},
    /* 375 */ {"Magolor (Kirby)", "Meia-calça"},
    /* 376 */ {"Muggshot (Sly Cooper)", "Maquiagem (pincel)"},
    /* 377 */ {"Macaco (Kung Fu Panda)", "Macaco hidráulico"},
    /* 378 */ {"Mike Forelli (Grand Theft Auto)", "Mikveh (banheira, jacuzzi)"},
    /* 379 */ {"Maggie Pesky (The Buzz on Maggie)", "Macaúba"},
    /* 380 */ {"Mavis Drácula (Hotel Transylvania)", "Mufa simples (mufa)"},
    /* 381 */ {"Muffy Dupar (Heathcliff & the Catillac Cats)", "Myfoodie beef stick (graveto)"},
    /* 382 */ {"Maven (Fortnite)", "Muffin (cupcake)"},
    /* 383 */ {"Maeve MCCAFFREY (Eureka Seven AO)", "MAFU mechanical feeding system"},
    /* 384 */ {"Mauvier (Fire Emblem)", "Amphora (inglês ou latim)"},
    /* 385 */ {"Mafalda (Mafalda)", "Moviola"},
    /* 386 */ {"Mave-chan (Sentou Yousei Shoujo Tasukete! Mave-chan)", "Mofo cheese (queijo cheddar, cottage, cheddar, queijo, ricota)"},
    /* 387 */ {"Muffy Crosswire (Arthur)", "Mafu Cameroon (Mafu Maduro, charuto, cachimbo)"},
    /* 388 */ {"Mafafa (Odisea Burbujas)", "Mefu fully-auto laminator"},
    /* 389 */ {"Mafia Boss (A Hat in Time)", "MAFU bowl feeder"},
    /* 390 */ {"Mibu Sayaka (The Irregular at Magic High School)", "Imposto (saco de dinheiro)"},
    /* 391 */ {"Impidimp (pokémon)", "Mob dungeon block (mob spawn, minecraft)"},
    /* 392 */ {"Mibuna (Naruto)", "Mi band (Smartwatch)"},
    /* 393 */ {"Mobambi (One Piece)", "Wampum"},
    /* 394 */ {"Mayberry (Helluva Boss)", "Hambúrguer (sanduíche)"},
    /* 395 */ {"Mabel Pines (Gravity Falls)", "Ampulheta"},
    /* 396 */ {"Moby Jerk (Johnny Bravo)", "Ambush (armadilha de urso, inglês)"},
    /* 397 */ {"Mibu Kyoshiro (Demon Eyes Kyo)", "Umbigo"},
    /* 398 */ {"Mibu Villager (Sekiro: Shadows Die Twice)", "Ampefy (antananarivo)"},
    /* 399 */ {"Mobo Bonanza (Bonanza Bros)", "Maypop (inglês)"},
    /* 400 */ {"Erza Scarlet (Fairy Tail)", "Resistor"},
    /* 401 */ {"Resetti (Animal Crossing)", "Roçadeira (cortador de grama)"},
    /* 402 */ {"Arsène (Persona 5 Royal)", "Ursinho de pelúcia (fofo, teddy bear)"},
    /* 403 */ {"Hasumi (Blue Archive)", "Hazmat (respirador facial)"},
    /* 404 */ {"Razorbeard (Rayman Origins)", "Rosário (terço)"},
    /* 405 */ {"Úrsula (Pequena Sereia)", "Risole (empanada, pastel, guioza)"},
    /* 406 */ {"Hizashi (Boku no Hero)", "Rosé Champagne (vinho, champagne)"},
    /* 407 */ {"Rosquinha (Gumball)", "Rosquinha (donut)"},
    /* 408 */ {"Irisviel (Fate/Grand Order)", "Rosa vermelha (Rosa)"},
    /* 409 */ {"Raspa do Tacho (Chicken Little)", "Rosbife (acém assado)"},
    /* 410 */ {"Warrod Sequen (Fairy Tail)", "Hat stand"},
    /* 411 */ {"Hot Dog Guy (Gumball)", "Ratatouille"},
    /* 412 */ {"Ratinho (Castelo Rá-Tim-Bum)", "Roton (He-man)"},
    /* 413 */ {"Rotomdex (Pokémon)", "Head mirror (medical head mirror, inglês)"},
    /* 414 */ {"Hattori (Brawlhalla)", "Ratoeira"},
    /* 415 */ {"Ardiloso (DC Comics)", "Roda do leme (roda do dharma, timão)"},
    /* 416 */ {"Radish Spirit (Spirited Away)", "Red Shell (Mario Kart)"},
    /* 417 */ {"Red X (DC Comics)", "Hadouken"},
    /* 418 */ {"Radovid (The Witcher)", "Head fish (peixe)"},
    /* 419 */ {"Rutabaga (BoJack Horseman)", "Rede de pesca"},
    /* 420 */ {"Hyness (Kirby)", "Uranus (saturno, inglês)"},
    /* 421 */ {"Randall Boggs (Monstros S.A.)", "Hand spinner (fidget spinner)"},
    /* 422 */ {"Aranha Negra (DC Comics)", "Renown health"},
    /* 423 */ {"Arnim Zola (Marvel)", "Hannya mask (Hannya, inglês)"},
    /* 424 */ {"Henry J. P. Waternoose (Monstros SA)", "Warner Bros. tower"},
    /* 425 */ {"Aron Langstrom (DC Comics)", "Urna eletrônica"},
    /* 426 */ {"Renji Abarai (Bleach)", "Hinge (dobradiça, inglês)"},
    /* 427 */ {"Rango (Rango)", "Rongorongo"},
    /* 428 */ {"Ranpha (Princess Connect! Re:Dive)", "Reunification 1962 (Hildegard Leest)"},
    /* 429 */ {"Araña Webb (Fairy Tail)", "Honey bun (inglês)"},
    /* 430 */ {"Hermes (Hércules)", "Hamsá"},
    /* 431 */ {"Wormwood (Don't Starve)", "Armadura peitoral"},
    /* 432 */ {"Rayman (Rayman)", "Roman dodecahedron"},
    /* 433 */ {"Riamu Yumemi (The Idolmaster)", "Remo de madeira (remo)"},
    /* 434 */ {"Homer Simpson (Simpsons)", "RoomeR drink"},
    /* 435 */ {"Romulus (Ratchet & Clank)", "Airmail (carta, inglês)"},
    /* 436 */ {"Rhumushi (dragon ball)", "Arma de gelo (Blue Rose's Freezing ice gun, pistola)"},
    /* 437 */ {"Himiko (Boku no Hero)", "Arm Cannon (Mega Man, inglês)"},
    /* 438 */ {"Hamphrey (Animal Crossing)", "Earmuff (fone de ouvido, inglês)"},
    /* 439 */ {"Humpty Dumpty (Shrek)", "Rampa"},
    /* 440 */ {"Horizon (Apex Legends)", "Horseshoe (ferradura, inglês)"},
    /* 441 */ {"Hairdresser Octopus (PaRappa the Rapper)", "Hurdle (inglês)"},
    /* 442 */ {"Roronoa Zoro (One Piece)", "Horn (chifre, inglês)"},
    /* 443 */ {"Harmony (Splatoon)", "Air remover"},
    /* 444 */ {"Hiro Hamada (Operação Big Hero)", "Harrier (SUV, inglês)"},
    /* 445 */ {"Hiriluk (One Piece)", "Aurora Lamp (LAVA Lamp, inglês)"},
    /* 446 */ {"Ura Urashima (Yu Yu Hakusho)", "RAREE-SHOW"},
    /* 447 */ {"Haruka (Sailor Moon)", "Wirework tree pendant"},
    /* 448 */ {"Hirofumi (The World Ends with You)", "Hair velcro roller (tiara dona florinda)"},
    /* 449 */ {"Herobrine (Minecraft)", "Harpsichord (piano, inglês)"},
    /* 450 */ {"Helsa von Eldritch (Hazbin Hotel)", "Wireless mouse (mouse)"},
    /* 451 */ {"Hildon (One Piece)", "Roleta"},
    /* 452 */ {"Roland (Brawlhalla)", "Rolinho de espuma (rolo de pintura)"},
    /* 453 */ {"Relâmpago Mcqueen (Carros)", "Rolo para massa"},
    /* 454 */ {"Rilla Roo (Crash Bandicoot)", "Roller (patins, inglês)"},
    /* 455 */ {"Halu-elu Dolu-do (Godzilla)", "Orelhão laranja (orelhão)"},
    /* 456 */ {"Horloge (a Bela e a fera)", "Relógio de chão"},
    /* 457 */ {"Hulk (Marvel)", "Airlock"},
    /* 458 */ {"Hellfire Flame (One-Punch Man)", "Air lift performance"},
    /* 459 */ {"Hellboy (Hellboy)", "Royal box"},
    /* 460 */ {"Ryuji Sakamoto (Persona 5 Royal)", "Raio-x (máquina de raio-x)"},
    /* 461 */ {"Arraia Jato (Ben 10)", "Rei de xadrez"},
    /* 462 */ {"Hatchan (One Piece)", "Russian nesting doll (boneca russa)"},
    /* 463 */ {"Urashima (One Piece)", "Hiroshima (nuvem de cogumelo)"},
    /* 464 */ {"Rasher (Animal Crossing)", "Hatcher eggs (incubadora, inglês)"},
    /* 465 */ {"Rachel (Satsuriku no Tenshi)", "Rachel Rotenberg sculpture"},
    /* 466 */ {"Orochi Yashiro (The King Of Fighters All Star)", "Rejudge (Anas Aremeyaw Anas's mask, inglês)"},
    /* 467 */ {"Arishok (Dragon Age II)", "air shaker (Air operated paint shaker)"},
    /* 468 */ {"Urshifu (Pokémon)", "Air cheff (Air fryer)"},
    /* 469 */ {"Rajab (Inazuma Eleven)", "Airship (zeppelim, dirigível, inglês)"},
    /* 470 */ {"Rex (Toy Story)", "Ruckus's exhaust (escape de moto, inglês)"},
    /* 471 */ {"Rocket (Guardiões da Galáxia)", "Raquete"},
    /* 472 */ {"Ragnaros (World of Warcraft)", "Ar condicionado"},
    /* 473 */ {"Rikum (dragon ball)", "Origami"},
    /* 474 */ {"Arco-Íris (DC Comics)", "Arco-íris"},
    /* 475 */ {"Arglas (Xenoblade Chronicles)", "Recolhedor para persiana"},
    /* 476 */ {"Rakshata (Code Geass)", "Hookshot (The Legend of Zelda)"},
    /* 477 */ {"Hako Kuroi (Naruto)", "Oreo cookie"},
    /* 478 */ {"Roquefort (Disney)", "Archive (archive box file organizer office, inglês)"},
    /* 479 */ {"Rigby (Apenas um Show)", "Rugby (troféu de rugby)"},
    /* 480 */ {"Rufus (Kim Possible)", "Erva-de-são-cristóvão"},
    /* 481 */ {"Heavy Tank (One-Punch Man)", "Raft (barco, balsa, jangada)"},
    /* 482 */ {"Ravena (DC Comics)", "Raven Graphite object"},
    /* 483 */ {"Hifumi Togo (Persona 5 Royal)", "Heavy machine gun"},
    /* 484 */ {"River (Armello)", "Hoverboard"},
    /* 485 */ {"Raphael (Alchemy Stars)", "Ervilha"},
    /* 486 */ {"Raffish Ralph (Berenstain Bears)", "Ravisher (Rosy ravisher Trove)"},
    /* 487 */ {"Rafiki (Disney)", "Revoke (carimbo, inglês)"},
    /* 488 */ {"Heavy Flo (Family Guy)", "Revive Grenade Fortnite"},
    /* 489 */ {"Heavy Weapons Guy (Team Fortress 2)", "Rev Up Launcher Beyblade"},
    /* 490 */ {"Rubeus (sailor moon)", "Arbusto"},
    /* 491 */ {"Ripto (Spyro)", "Rapadura"},
    /* 492 */ {"Ribbon Girl (ARMS)", "Hypnotic wheel"},
    /* 493 */ {"Happy Meek (Uma Musume)", "Erbium oxide (LED, radiômetro)"},
    /* 494 */ {"Hopper (Vida de Inseto)", "Rubber eraser (borracha, eraser)"},
    /* 495 */ {"Rubble (PAW Patrol)", "Hubble"},
    /* 496 */ {"Hebiichigo (Naruto)", "Rabicho"},
    /* 497 */ {"RoboCop (RoboCop)", "Airbag"},
    /* 498 */ {"Robo Fizz (Helluva Boss)", "Raw beef (minecraft)"},
    /* 499 */ {"Rapa pup (Invizimals)", "Wrap up (tray wrapper)"},
    /* 500 */ {"Lisa Simpson (Os Simpsons)", "Laces (laço, lacinho, gravata borboleta, cadarço)"},
    /* 501 */ {"Alistar (League of Legends)", "Lustre"},
    /* 502 */ {"Lysandre (Pokémon)", "Wilson (bola WIlson)"},
    /* 503 */ {"Lusamine (Pokémon)", "Elysium (exoskeleton, esqueleto)"},
    /* 504 */ {"Lucy Heartfilia (Fairy Tail)", "Laser"},
    /* 505 */ {"Alisa Illinichina (God Eater)", "Lazúli"},
    /* 506 */ {"Yellow Sage (Jak and Daxter)", "Óleo de soja (soja)"},
    /* 507 */ {"Alzack (Fairy Tail)", "Olho de sogra"},
    /* 508 */ {"Lucia Fex (Promare)", "Laço da Verdade"},
    /* 509 */ {"Elizabeth (Nanatsu no Taizai)", "Luz de palco"},
    /* 510 */ {"Lotso (Toy Story)", "Lattice (inglês)"},
    /* 511 */ {"Aldith (Pokémon)", "Leaded gasoline (gasolina, inglês)"},
    /* 512 */ {"Aladdin (Aladdin)", "Leyden jar"},
    /* 513 */ {"Leão da montanha (Snagglepuss)", "Altímetro"},
    /* 514 */ {"Ultraman (Ultraman)", "Halter"},
    /* 515 */ {"Eilietta Lash (Zenonzard The Animation)", "Little boy (bomba atômica)"},
    /* 516 */ {"Wild Jango (Mega Man)", "Light show (lase, inglês)"},
    /* 517 */ {"Light Yagami (Death Note)", "Latke"},
    /* 518 */ {"Ly the Fairy (Rayman Origins)", "Alto-falante (caixa de som, amplificador, som)"},
    /* 519 */ {"Yaldabaoth (Xenoblade Chronicles)", "Load up (caminhão)"},
    /* 520 */ {"Leôncio (Pica-Pau)", "Lança"},
    /* 521 */ {"Yolanda (BoJack Horseman)", "Lanterna"},
    /* 522 */ {"Lina Inverse (Slayers)", "Linen (linho, inglês)"},
    /* 523 */ {"Elaine Marley (Escape from Monkey Island)", "LANmark (carretel)"},
    /* 524 */ {"Leonardo (Zootopia)", "Lunaria"},
    /* 525 */ {"Leni Loud (The Loud House)", "Lunula (Gold Lunula, inglês)"},
    /* 526 */ {"Lunch (dragon ball)", "Lanchonete (Estufa para salgados)"},
    /* 527 */ {"Link (Nintendo)", "Língua de sogra (apito)"},
    /* 528 */ {"Lyon Vastia (Fairy Tail)", "Leon Veerman Vergankelijkheid"},
    /* 529 */ {"Leon Powalski (Star Fox)", "Line up junção fita led"},
    /* 530 */ {"Limstella (Fire Emblem)", "Lamaze vagalume"},
    /* 531 */ {"Alameda Slim (Disney)", "Limeade (limonada)"},
    /* 532 */ {"Luminary (Dragon Quest)", "Alumínio"},
    /* 533 */ {"Elmo Monster (Sesame Street)", "Elmo medieval (elmo)"},
    /* 534 */ {"Elmer Fudd (Looney Tunes)", "Lamiro Microcurrent"},
    /* 535 */ {"Lymle (Star Ocean)", "Lamely"},
    /* 536 */ {"Elma Chiti (Inazuma Eleven)", "Olho mágico"},
    /* 537 */ {"Limãograb (Hora de aventura)", "Olmec (Moai)"},
    /* 538 */ {"Alma V (Calamity of a Zombie Girl)", "Almofariz (pilão)"},
    /* 539 */ {"Willie Wumpa Cheeks (Crash Bandicoot)", "Lâmpada Árabe"},
    /* 540 */ {"Leroy Smith (Tekken)", "Olho de Hórus"},
    /* 541 */ {"Willard (Jak and Daxter)", "Lard (pudim, inglês)"},
    /* 542 */ {"L-Ron (DC Comics)", "Laranja"},
    /* 543 */ {"Leroy Mullins (South Park)", "Alarme (despertador)"},
    /* 544 */ {"Lire Eryuell (Grand Chase)", "Lareira elétrica (forno)"},
    /* 545 */ {"Lorelei (Alchemy Stars)", "Laurel (loura, inglês)"},
    /* 546 */ {"Leraje (Magi-The Labyrinth Of Magic)", "Larch (pinheiro, inglês)"},
    /* 547 */ {"Lorax (Lorax)", "Alargador"},
    /* 548 */ {"Leroy Fruit Funny (LOLOGO)", "Leroy Fresquez (gaiola, jaula)"},
    /* 549 */ {"Leorio Paradinight (Hunter x Hunter)", "Larp light (Conquest of Mythodea)"},
    /* 550 */ {"Lili Zanotto (Psychonauts)", "Lalá estrela"},
    /* 551 */ {"Lilith (Night Warriors)", "Lolita (boneca de pano)"},
    /* 552 */ {"Lei Wulong (Tekken)", "Llewellyn (Rolling Ball Sculpture)"},
    /* 553 */ {"Lula Molusco (Bob Esponja)", "Lua lâmina (faca meia lua)"},
    /* 554 */ {"Lulu Yurigasaki (YuriKuma Arashi)", "Loller pelham"},
    /* 555 */ {"Lyle Lipton (Helluva Boss)", "Olho de lula (olho)"},
    /* 556 */ {"Lalasha (The Groovenians)", "LELEJU selfie ring light"},
    /* 557 */ {"Lil Acorn (My Life as a Teenage Robot)", "Lilac object grabber (object grabber)"},
    /* 558 */ {"Lilia Vanrouge (Twisted Wonderland)", "Óleo de oliva (azeites)"},
    /* 559 */ {"Lola Bunny (O Show dos Looney Tunes)", "Lollipop (pirulito)"},
    /* 560 */ {"Luscious (Brimstone and The Borderhounds)", "Lashes (cílios)"},
    /* 561 */ {"Losha Tarkon (Star Wars)", "Lixo tóxico (barril)"},
    /* 562 */ {"Lechonk (Pokémon)", "Lichen (musgo, mofo, inglês)"},
    /* 563 */ {"LeChimp (Monkey Island)", "Algemas"},
    /* 564 */ {"Ligeirinho (O Show dos Looney Tunes)", "Lixeira (cesto de lixo)"},
    /* 565 */ {"Lucho Libre (Kikoumba Crown Down)", "Yellow jewel (joia da mente, inglês)"},
    /* 566 */ {"La Chacha (Patoruzito)", "Lash chair (cadeira, rattan)"},
    /* 567 */ {"Leo Chockers (Let's Go Luna!)", "Logic puzzle rotating roller"},
    /* 568 */ {"Luigi Vendetta (Kick Buttowski)", "Eyelash fan"},
    /* 569 */ {"La Chapi (Deviantart)", "Oil ship (navio, inglês)"},
    /* 570 */ {"All Cosmos (Katamari)", "Lagosta"},
    /* 571 */ {"Lakitu (Nintendo)", "Algodão-doce"},
    /* 572 */ {"El Condor Pasa (Uma Musume)", "Lagoon (inglês)"},
    /* 573 */ {"ElecMan.EXE (Mega Man)", "Locomotiva (trem)"},
    /* 574 */ {"Alegria (Divertida Mente)", "Lacre"},
    /* 575 */ {"Algalon (World of Warcraft)", "Algal ball (inglês)"},
    /* 576 */ {"Alec Johnson (Cyberpunk 2077)", "Lockjaw ladder grip"},
    /* 577 */ {"Licca Kusunoki (God Eater)", "Leak control flange"},
    /* 578 */ {"Wally Wackford (Helluva Boss)", "Alcova gazebo"},
    /* 579 */ {"Lock-up (DC Comics)", "Helicóptero (autogiro)"},
    /* 580 */ {"Lifesaver (Mega Man)", "Alface"},
    /* 581 */ {"Louva-deus (Kung Fu Panda)", "Holofote"},
    /* 582 */ {"Lavenda (dragon ball)", "Alavanca (minecraft)"},
    /* 583 */ {"Levy McGarden (Fairy Tail)", "Luva da máquina do tempo (Hora de Aventura)"},
    /* 584 */ {"Alfred (MAD)", "Olho de Verdade (The Legend of Zelda)"},
    /* 585 */ {"Elfillin (Nintendo)", "Álveolos (pulmões)"},
    /* 586 */ {"Lavish (Charmaine Grand - Marvel)", "Lavash (crepe, pão sírio, tapioca, fécula, inglês)"},
    /* 587 */ {"Wolfgang (Don't Starve)", "La vaca (touro de wall street)"},
    /* 588 */ {"Olho-vivo (Toy Story)", "Lviv art suitcase"},
    /* 589 */ {"Olivia Oblige (Bravely Default)", "Luva do poder (Nintendo)"},
    /* 590 */ {"Alba Singh (Alba: A Wildlife Adventure)", "Lápis"},
    /* 591 */ {"Loopty Goopty (Helluva Boss)", "Lápide"},
    /* 592 */ {"Lopunny (Pokémon)", "Alpine F1"},
    /* 593 */ {"Lobo Mau (Deu a Louca na Chapeuzinho)", "Álbum de música (disco)"},
    /* 594 */ {"Elo Perdido (Monstros vs. Alienígenas)", "Labirinto"},
    /* 595 */ {"El Blaze (Virtua Fighter)", "Lapela (microfone, boom mic)"},
    /* 596 */ {"LePage (Tom and Jerry: Snowman's Land)", "LPG cylinder (botijão)"},
    /* 597 */ {"Alpacaman (One Piece)", "Alpaca head keychain"},
    /* 598 */ {"Labofo (Dofus)", "Albufeira globe roundabout"},
    /* 599 */ {"Ali-Baba (Code of Princess)", "La papa (batata)"},
    /* 600 */ {"Chise Asukagawa (Gridman)", "Giz de cera (giz)"},
    /* 601 */ {"Justin (Total Drama Island)", "Chest skeleton (rib cage)"},
    /* 602 */ {"Jason (Sexta-Feira 13)", "Chasen"},
    /* 603 */ {"Jasmine (princesa)", "Jasmine Clark's sculpture"},
    /* 604 */ {"Chizuru Kagura (The King Of Fighters All Star)", "Gêiser (Geyser)"},
    /* 605 */ {"José Luis (Cyberpunk 2077)", "Chisel"},
    /* 606 */ {"Shisui Uchiha (Naruto)", "Jesse James's Raiden"},
    /* 607 */ {"Jessica Rabbit (Disney)", "Jessica Kay's sculpture"},
    /* 608 */ {"Joseph (Free Fire)", "Joseph Seltzer's Abstract Metal Sculpture"},
    /* 609 */ {"José Porla (Fairy Tail)", "Joia do espaço (Marvel)"},
    /* 610 */ {"Shuu Tsukiyama (Tokyo Ghoul)", "Jet ski (lancha)"},
    /* 611 */ {"Jet The Hawk (Sonic)", "Jato de tinta (impressora)"},
    /* 612 */ {"Ashton Anchors (Star Ocean)", "Jatinho (jato, avião)"},
    /* 613 */ {"ShadowMan EXE (Mega Man)", "Joia do tempo (Marvel)"},
    /* 614 */ {"Chowder (Chowder)", "Ishi-dōrō (Dai-dōrō)"},
    /* 615 */ {"Shou Daliuwan (Scissor Seven)", "Shuttlecock (inglês)"},
    /* 616 */ {"Jude sharp (Inazuma Eleven)", "Jato de gesso"},
    /* 617 */ {"Watchdog Man (One-Punch Man)", "Jato de água (lavadora de alta pressão)"},
    /* 618 */ {"Jet-Vac (Skylanders)", "Jet fins (nadadeira)"},
    /* 619 */ {"Jet Propulsion (Ready Jet Go!)", "JBL (Caixa de som, amplificador, som, alto-falante)"},
    /* 620 */ {"Janissary (DC Comics)", "Jeans (calça)"},
    /* 621 */ {"Shun de Andrômeda (Saint Seiya)", "Chantilly"},
    /* 622 */ {"Xananab (Donkey Kong)", "Xenônio"},
    /* 623 */ {"Janemba (dragon ball)", "Genoma (alelo, cromossomo)"},
    /* 624 */ {"Jin Hazuki (Blade & Soul)", "Junior maxi car seat"},
    /* 625 */ {"Shenlong (dragon ball)", "Janela"},
    /* 626 */ {"Chinjao (One Piece)", "Gengibre"},
    /* 627 */ {"Jenny Wakeman (My Life as a Teenage Robot)", "Jenga"},
    /* 628 */ {"Jennifer Peach (Kandagawa Jet Girls)", "Genuflexório"},
    /* 629 */ {"Johnny Bravo (Johnny Bravo)", "Chin up bar outdoor (pull up bar)"},
    /* 630 */ {"James P. Sullivan (Monstros S.A.)", "Chimes (carrilhão, inglês)"},
    /* 631 */ {"Yoshimitsu (Tekken)", "Jammed finger (Finger splint, inglês)"},
    /* 632 */ {"Jiminy Cricket (Kingdom Hearts)", "Chaminé"},
    /* 633 */ {"Jim McSweeney (Sly Cooper)", "Jim McKenzie crown"},
    /* 634 */ {"Jiemma Orland (Fairy Tail)", "Chimarrão"},
    /* 635 */ {"Jimmy Lizard (Hoodwinked)", "Jim Wheeler's Pacific Rim"},
    /* 636 */ {"Shamash (Shaman King)", "Joia de majorca (colar, brinco, joia)"},
    /* 637 */ {"Shimiko (Blue Archive)", "Jamaican duho"},
    /* 638 */ {"Edge Maverick (Star Ocean)", "Chamfering tile (inglês)"},
    /* 639 */ {"Jumba Jookiba (Lilo & Stitch)", "Chimbal"},
    /* 640 */ {"Charizard (Pokémon)", "Churros"},
    /* 641 */ {"Charada (DC Comics)", "Gerador (motor)"},
    /* 642 */ {"Sharon Spitz (Braceface)", "Jornal"},
    /* 643 */ {"Charmy (Sonic)", "Sherman crab (LANMO Sherman Crab)"},
    /* 644 */ {"Chihiro (Spirited Away)", "Cheerer (Pom-poms)"},
    /* 645 */ {"Charlotte Amande (One Piece)", "Shrill Voca (Warframe)"},
    /* 646 */ {"Jorge (Yu Yu Hakusho)", "Churchkhela"},
    /* 647 */ {"Shrek (Shrek)", "Shuriken"},
    /* 648 */ {"Girafales (Prof. Girafales - chaves em desenho)", "Sheriff (distintivo, FBI)"},
    /* 649 */ {"Sherry Blendy (Fairy Tail)", "Echarpe (cachecol)"},
    /* 650 */ {"Gelus (Death Note)", "Jalousie (persiana, inglês)"},
    /* 651 */ {"Gelado (Rei gelado - Hora de Aventura)", "Gillette"},
    /* 652 */ {"Julien (Madagascar)", "Chi Lin"},
    /* 653 */ {"Jalmack (One Piece)", "Julia Morison Headcase"},
    /* 654 */ {"Ajeel Ramal (Fairy Tail)", "Chiller (resfriador, inglês)"},
    /* 655 */ {"Jellal (Fairy Tail)", "Shillalah (cajado, bengala)"},
    /* 656 */ {"Julia Chang (Tekken)", "Gelo gel"},
    /* 657 */ {"Ashley Graham (Resident Evil)", "Chalkboard eraser"},
    /* 658 */ {"Jill Valentine (Resident Evil)", "Xilofone"},
    /* 659 */ {"Jill Pill (BoJack Horseman)", "Jalopy (inglês)"},
    /* 660 */ {"Chiyo Shuzenji (Boku no Hero)", "Chichá do Cerrado"},
    /* 661 */ {"Judge Dredd (Judge Dredd)", "Joshua Tobey Voice on the Wind"},
    /* 662 */ {"Joe Chin (PaRappa the Rapper)", "Xuxinha de cabelo"},
    /* 663 */ {"Josh Mankey (Kim Possible)", "Josh Mayhem ballon dog (cachorro de balão)"},
    /* 664 */ {"Shuji Hanma (Tokyo Revengers)", "Chichu art museum Shipyard Works Bow with Hole"},
    /* 665 */ {"Judge Lee (Judge Lee Han Young)", "Jewish law (ten commandments, inglês)"},
    /* 666 */ {"Chiyo Chichi (Azumanga Daioh)", "666 (pentagrama)"},
    /* 667 */ {"Chichiyaku (Spirited Away)", "Judge gavel (martelo de juiz, inglês)"},
    /* 668 */ {"Shuji Fujikawa (Killer Killer)", "Josh Fradis pumpkin"},
    /* 669 */ {"Jujuba (Princesa Jujuba - Hora de Aventura)", "Jujuba"},
    /* 670 */ {"Jack Skellington (The Nightmare Before Christmas)", "Jigsaw (quebra-cabeça, inglês)"},
    /* 671 */ {"Jack The Ripper (Fate/Grand Order)", "Chicote"},
    /* 672 */ {"Chiquinha (Chaves)", "Check-in (campainha sino)"},
    /* 673 */ {"Shikkui Makabe (Boku no Hero)", "Chuck EM (Runner chuck EM sensor, prendedor de roupa)"},
    /* 674 */ {"Chucrute (Vida de Inseto)", "Xícara"},
    /* 675 */ {"Jigglypuff (Pokémon)", "Chocalho (maraca)"},
    /* 676 */ {"Ash Ketchum (Pokémon)", "Oshkosh L-ATV"},
    /* 677 */ {"Shukaku (Naruto)", "Chicago bean"},
    /* 678 */ {"Jack Phantom (Danny Phantom)", "Checkoff box 3D"},
    /* 679 */ {"Chico bento (Turma da Mônica)", "Shock absorber (inglês)"},
    /* 680 */ {"Chaves (Chaves em desenho)", "Chives (cebolinha, inglês)"},
    /* 681 */ {"Shift (DC Comics)", "Chaveta"},
    /* 682 */ {"Jeff Andonuts (EarthBound)", "Chafing dish buffet (dish buffet)"},
    /* 683 */ {"Chifuyu Matsuno (Tokyo Revengers)", "JUFUM sound proof foam"},
    /* 684 */ {"Jeff Randell (Clarence)", "Chafariz"},
    /* 685 */ {"Juvia Lockser (Fairy Tail)", "Shovel (pá, pá de neve, inglês)"},
    /* 686 */ {"Shifu Choushou (Ikki Tousen)", "Chave de gelo (Ice Key Banjo-Kazooie)"},
    /* 687 */ {"JFK (Clone High)", "Chave de grifo (Chave de tubo)"},
    /* 688 */ {"Jeff Fischer (American Dad)", "Chave de fenda"},
    /* 689 */ {"Shifu Pigsy (DC Comics)", "Chave pé de galo"},
    /* 690 */ {"Chapeuzinho (Deu a Louca na Chapeuzinho)", "Chip SIM"},
    /* 691 */ {"Japeth (hoodwinked)", "Chupeta"},
    /* 692 */ {"She-Bang (DC Comics)", "Chapinha"},
    /* 693 */ {"Witch Bomber (Bomberman World)", "Chip de memória RAM (memória RAM, RAM)"},
    /* 694 */ {"Jabra (One Piece)", "Chipper (inglês)"},
    /* 695 */ {"Chapolin Colorado (Chaves animado)", "Washbowl (pia, inglês)"},
    /* 696 */ {"Chop Chop Master Onion (PaRappa the Rapper)", "Chup-chup"},
    /* 697 */ {"Chabwick (Animal Crossing)", "Chapéu KKK"},
    /* 698 */ {"Shaiapouf (Hunter x Hunter)", "Chapéu viseira (boné, cap)"},
    /* 699 */ {"Sheba Beboporeba (Felix the Cat)", "Chapéu Bobo da Corte"},
    /* 700 */ {"Cassios (Saint Seiya)", "Kisses Candy"},
    /* 701 */ {"Gaston (Meet the Robinsons)", "Ghost trap (Ghostbusters)"},
    /* 702 */ {"Kuzen Yoshimura (Tokyo Ghoul)", "Caça-níqueis"},
    /* 703 */ {"Gossamer (O Show dos Looney Tunes)", "Gas mask (hazmat, respirador facial, inglês)"},
    /* 704 */ {"Akos Hu (Naraka Bladepoint)", "Quasar"},
    /* 705 */ {"Gazella (Zootopia)", "Guzzler helmet"},
    /* 706 */ {"Casey Jones (Teenage Mutant Ninja Turtles)", "Oxigênio (cilindro de oxigênio)"},
    /* 707 */ {"Cascão (Turma da Mônica)", "Casquinha de sorvete"},
    /* 708 */ {"Casey Femur (Strangers in Paradise)", "Cassava (aipim, mandioca, inglês)"},
    /* 709 */ {"Gasparzinho (Gasparzinho)", "Xbox (Playstation, videogame)"},
    /* 710 */ {"Katsuki (Boku no Hero)", "Caduceu"},
    /* 711 */ {"Gato de Botas (Shrek)", "Cadeado"},
    /* 712 */ {"Kotennyo (Yu Yu Hakusho)", "Cotonete"},
    /* 713 */ {"Guy Diamante (Trolls)", "Kate MccGwire Feather Sculpture"},
    /* 714 */ {"Cutter (Monstros S.A.)", "Coador"},
    /* 715 */ {"Kate Alen (F-Zero)", "Kettle (chaleira, inglês)"},
    /* 716 */ {"Kitajima (One Piece)", "Cottage cheese pancake"},
    /* 717 */ {"Kid Cat (Animal Crossing)", "Kodak (câmera, webcam)"},
    /* 718 */ {"Gato Félix (Gato Félix)", "Catavento"},
    /* 719 */ {"Yuktopus (Crash Bandicoot)", "Catapulta"},
    /* 720 */ {"Conserta Felix Jr. (Detona Ralph)", "Cone de sinalização"},
    /* 721 */ {"Candy Kong (Donkey Kong)", "Canudo"},
    /* 722 */ {"Cannonbolt (Ben 10)", "Canon (canhão, ingês)"},
    /* 723 */ {"Koenma (Yu Yu Hakusho)", "Gnômon (relógio de sol)"},
    /* 724 */ {"Kanaria (hunter x hunter)", "Canner (panela de pressão, inglês)"},
    /* 725 */ {"Canelinha (Hora de aventura)", "Caneleira (com espinhos)"},
    /* 726 */ {"Ken Ishiyama (Boku no Hero)", "Gancho"},
    /* 727 */ {"Kinoko (Boku no Hero)", "Gangorra"},
    /* 728 */ {"Gon Freecss (Hunter x Hunter)", "Cone de festa"},
    /* 729 */ {"Cain Barzad (Nanatsu no Taizai)", "Cannabis (erva)"},
    /* 730 */ {"Kami-Sama (dragon ball)", "Camisa"},
    /* 731 */ {"Kumadori (One Piece)", "Cometa"},
    /* 732 */ {"Gaimon (One Piece)", "Cayman Rattan Decorative Spheres"},
    /* 733 */ {"Koyomi Yamanaka (SSSS. DYNAZENON)", "Goma de mascar (chiclete)"},
    /* 734 */ {"Gyomei Himejima (Demon Slayer)", "Cama de rede (rede de descanso)"},
    /* 735 */ {"Gimlet (One Piece)", "Cama elástica (pula pula)"},
    /* 736 */ {"Kumashi (One Piece)", "Kimchi"},
    /* 737 */ {"Kamek (Nintendo)", "Chemical feed pump (inglês)"},
    /* 738 */ {"Camofrog (Animal Crossing)", "Camfo (máquina, costura)"},
    /* 739 */ {"Gumball Watterson (Gumball)", "Compasso"},
    /* 740 */ {"Garça (Kung Fu Panda)", "Coração"},
    /* 741 */ {"Kratos (God of War)", "Guarda-chuva"},
    /* 742 */ {"Crank Casey (Robôs)", "Carrinho de compras"},
    /* 743 */ {"Kermit (muppets)", "Grama"},
    /* 744 */ {"Groribas (One-Punch Man)", "Coroa real (coroa)"},
    /* 745 */ {"K. Rool (Donkey Kong)", "Grelha"},
    /* 746 */ {"Crash Bandicoot (Crash Bandicoot)", "Carruagem"},
    /* 747 */ {"Greg Heffley (Diary of a Wimpy Kid)", "Cracker"},
    /* 748 */ {"Garfield (Garfield)", "Gravata"},
    /* 749 */ {"Creeper (Minecraft)", "Corbel (mísula, annulet, inglês)"},
    /* 750 */ {"Callista (Shrek)", "Óculos (juliete)"},
    /* 751 */ {"Glutão (Ben 10)", "Guilhotina"},
    /* 752 */ {"Klonoa (Klonoa)", "Calendário"},
    /* 753 */ {"Gollum (Lord Of The Rings)", "Colmeia"},
    /* 754 */ {"Glória (Madagáscar)", "Colher"},
    /* 755 */ {"Kolulu (Zatch Bell)", "Chloe Lennon Unearthed"},
    /* 756 */ {"Gol Acheron (Jak and Daxter)", "Galocha (botas)"},
    /* 757 */ {"Gallaxhar (Monstros vs. Alienígenas)", "Galão de água"},
    /* 758 */ {"Gullivarrr (Animal Crossing)", "Cola de vidro (cola)"},
    /* 759 */ {"Galbo (Kirby)", "Globo de neve (snowglobe)"},
    /* 760 */ {"Goushi Asougi (Sword Art Online)", "Caixa SOS (SOS)"},
    /* 761 */ {"Kajetan (Little Amadeus)", "Caixa d'água"},
    /* 762 */ {"Kai Ijuuin (Shadowverse)", "Coxinha"},
    /* 763 */ {"Kiyoshi Mitarai (Yu Yu Hakusho)", "Cachimbo"},
    /* 764 */ {"Kyojuro (Demon Slayer)", "Cachorro-quente"},
    /* 765 */ {"Gajeel (Fairy Tail)", "Caixa eletrônico (caixa registradora)"},
    /* 766 */ {"Koji Shinomiya (Gakuen Heaven)", "Queijo cheddar (cheddar, queijo, ricota)"},
    /* 767 */ {"Kōji Kōda (Boku no Hero)", "Caixa de correios"},
    /* 768 */ {"Kiyoshi Fujino (Prison School)", "Cacho de uva (uva, grape)"},
    /* 769 */ {"Cash Buckzo (Helluva Boss)", "Caixa preta"},
    /* 770 */ {"Kuki Sanban (KND)", "Khakis (calça, shorts, inglês)"},
    /* 771 */ {"Cacoete (Toy Story)", "Cacto"},
    /* 772 */ {"Gaguinho (O Show dos Looney Tunes)", "Cocaína"},
    /* 773 */ {"Kakamora (Moana)", "Guacamole"},
    /* 774 */ {"Kakarotto (Dragon Ball)", "Cocar"},
    /* 775 */ {"Cu Chulainn (Smite)", "Cocklepot on stand"},
    /* 776 */ {"Kakashi (Naruto)", "Cacau Show (bombom, ferrero rocher)"},
    /* 777 */ {"QQQ (F-Zero)", "Coca-cola"},
    /* 778 */ {"Coq au Vin (Bistro Heroes)", "Kick-off tee (bola de futebol, bola, rugby)"},
    /* 779 */ {"Kick Buttowski (Kick Buttowski)", "Kickapoo prayer stick"},
    /* 780 */ {"Geva Storke (Final Fantasy)", "KFC"},
    /* 781 */ {"Gevo Trangas (Inazuma Eleven)", "Cavadeira boca de lobo (boca de lobo)"},
    /* 782 */ {"Covinhas (Mob Psycho 100)", "Coffin (caixão, inglês)"},
    /* 783 */ {"Kaufman (The Remarried Empress)", "Café da manhã (bandeja de café da manhã)"},
    /* 784 */ {"A caveira (F-Zero)", "Caveira (esqueletos)"},
    /* 785 */ {"Cavaleiro Sem Licença (One-Punch Man)", "Cavalo de mola"},
    /* 786 */ {"Weakfish (ThunderCats)", "Koi fish cat teaser (vara de pescar)"},
    /* 787 */ {"Kif Kroker (Futurama)", "Cavaquinho (violão)"},
    /* 788 */ {"Kufa Vampir (Assassin's Pride)", "Agave Furcraea (agave, sisal)"},
    /* 789 */ {"Kofi Pizza (Steven Universe)", "Key fob (chaveiro, inglês)"},
    /* 790 */ {"Cabeça de Batata (Toy Story)", "Cápsula (pílula)"},
    /* 791 */ {"Capote (One Piece)", "Cabide"},
    /* 792 */ {"Gabon (Kirby)", "Cabine doctor who"},
    /* 793 */ {"Aqua Bomber (Bomberman World)", "Copo medidor (copo)"},
    /* 794 */ {"Cooper (Trolls)", "Cubo rubik (cubo mágico)"},
    /* 795 */ {"Eggplant Wizard (Kid Icarus)", "Capelo"},
    /* 796 */ {"Cabaji (One Piece)", "Capa de chuva"},
    /* 797 */ {"Oogie Boogie (Mundo de Jack)", "Cubículo de média tensão"},
    /* 798 */ {"Kubfu (Pokémon)", "Quibe frito (quibe)"},
    /* 799 */ {"Koopa Paratroopas (Nintendo)", "Cobweb (teia, teia de aranha, inglês)"},
    /* 800 */ {"Fuzzy Wuzzy (Pororo the Little Penguin)", "Fezes (bosta)"},
    /* 801 */ {"Faust (One Piece)", "Vestiário (guarda-roupa)"},
    /* 802 */ {"Fussenpepper (PaRappa the Rapper)", "Visão noturna (óculos de visão noturna)"},
    /* 803 */ {"Fosse McDonald (South Park)", "Vasma Robotics (braço robô)"},
    /* 804 */ {"Face Ripper (One-Punch Man)", "Vassoura (besom)"},
    /* 805 */ {"Fizzle (My Little Pony)", "Vessel (TKA)"},
    /* 806 */ {"Faize Sheifa (Star Ocean)", "Foice de gelo (Dota 2)"},
    /* 807 */ {"Fuzzy Confusão (As Meninas Super Poderosas)", "Faiscador anti raio"},
    /* 808 */ {"Phosphorus (DC Comics)", "Fusível"},
    /* 809 */ {"Vespa (Marvel)", "Fuse block"},
    /* 810 */ {"Feiticeira (He-Man)", "Fita isolante"},
    /* 811 */ {"Fada do Dente (A Origem dos Guardiões)", "Fita adesiva"},
    /* 812 */ {"Feitan (Hunter x Hunter)", "Fio dental"},
    /* 813 */ {"Fathom (Lord Fathom - Disney)", "Fita métrica"},
    /* 814 */ {"Vitruvius (LEGO)", "Vitória-régia"},
    /* 815 */ {"Vitaly (Madagáscar)", "Foot lamp (foot, pé)"},
    /* 816 */ {"Futoshi (Darling in the Franxx)", "Fetish (Merrit Johnson)"},
    /* 817 */ {"Fat Gum (Boku no Hero)", "Photo cutter (alicate, seizer, tesoura)"},
    /* 818 */ {"Vato Falman (Fullmetal Alchemist)", "Fotovoltaico (painel solar)"},
    /* 819 */ {"Futaba (Persona 5 Royal)", "Fatia de bolo (bolo)"},
    /* 820 */ {"Vinsmoke Niji (One Piece)", "Vans (tênis, sapato)"},
    /* 821 */ {"Vander Decken (One Piece)", "Ventilador"},
    /* 822 */ {"Phonon (Under Night In-Birth)", "Veneno"},
    /* 823 */ {"Venom (Homem-Aranha)", "Venom's tongue (língua do venom, inglês)"},
    /* 824 */ {"Van Hohenheim (Fullmetal Alchemist)", "Ovenware (vasilha, tigela, inglês)"},
    /* 825 */ {"Vanellope (Detona Ralph)", "Funil"},
    /* 826 */ {"Finch (Xenoblade Chronicles)", "Fungicida"},
    /* 827 */ {"Finkelstein (O Estranho Mundo de Jack)", "Van de graaf"},
    /* 828 */ {"Phan Phan (Kirby)", "Fone de ouvido (earmuff)"},
    /* 829 */ {"Fen Bock (One Piece)", "Finn bottle opener"},
    /* 830 */ {"Vamos (Dark Souls)", "Foam scrap"},
    /* 831 */ {"Fumio Daimidō (Food Wars!)", "Foam dividers"},
    /* 832 */ {"Fomantis (pokémon)", "Fumante de alimentos"},
    /* 833 */ {"Fumio Mimura (BNA)", "Foam machine"},
    /* 834 */ {"Fami Harukaze (Ojamajo Doremi Na-i-sho)", "Fumarola"},
    /* 835 */ {"Fa Mulan (Disney)", "Female urinal"},
    /* 836 */ {"Fumio Chitose (Hairpin Double)", "Famichiki (nugget, KFC)"},
    /* 837 */ {"Fumikage (Boku no Hero)", "Fumegador"},
    /* 838 */ {"Femme Fatale (The Powerpuff Girls)", "Vamvo (projetor)"},
    /* 839 */ {"Vampirella (Comics)", "Vampíro (dentadura de vampiro)"},
    /* 840 */ {"Freeza (dragon ball)", "Frezer (geladeira)"},
    /* 841 */ {"Fred (Big Hero 6)", "Fritas (batata frita)"},
    /* 842 */ {"Francisca (Kirby)", "Frango assado"},
    /* 843 */ {"Vermoud (dragon ball)", "Formigueiro"},
    /* 844 */ {"Freyr (Fire Emblem Heroes)", "Ferrero Rocher (bombom, cacau show)"},
    /* 845 */ {"Vril Dox (DC Comics)", "Fralda"},
    /* 846 */ {"Frajola (O Show dos Looney Tunes)", "Frigideira"},
    /* 847 */ {"Forky (Toy Story)", "Furacão (tornado)"},
    /* 848 */ {"Fru-Fru (My Life as a Teenage Robot)", "Fire Flower (Super Mario)"},
    /* 849 */ {"Ferb (Phineas e Ferb)", "Ferro de passar"},
    /* 850 */ {"Felicia (Darkstalkers)", "Velocímetro"},
    /* 851 */ {"Flit (Pocahontas)", "Filtro"},
    /* 852 */ {"Avelon (One Piece)", "Volante"},
    /* 853 */ {"Velma (Scooby-doo)", "Flâmula"},
    /* 854 */ {"Florinda (Dona Florinda)", "Vela aromática (vela)"},
    /* 855 */ {"Val Little (Monstros S.A.)", "Flail (mangual, clava, inglês)"},
    /* 856 */ {"Flecha (Zootopia)", "Flush hatch"},
    /* 857 */ {"Flik (Vida de inseto)", "Floco de neve"},
    /* 858 */ {"Wolverine (Marvel)", "Válvula"},
    /* 859 */ {"Philip J. Fry (Futurama)", "Folha de papel (papel)"},
    /* 860 */ {"Fishstick (Fortnite)", "Fiji Wasekaseka (colar)"},
    /* 861 */ {"Vegeta (Dragon Ball)", "Feijão tropeiro (feijão)"},
    /* 862 */ {"Vishnu (Marvel)", "Vagina (vulva didática, útero)"},
    /* 863 */ {"Fujimaru-kun (Fuji Shoji)", "Fujiyama (montanha, relevo)"},
    /* 864 */ {"Vajarois (Little Witch Academia)", "Fichário (caderno, livro)"},
    /* 865 */ {"Vigilante (DC Comics)", "OAFISHLY Ab Roller Wheel"},
    /* 866 */ {"Fuji Shikimori (Shikimori Isn't Just A Cutie)", "Fecho para janela (trinco, latch, fecho)"},
    /* 867 */ {"Fuji Kiseki (Uma Musume)", "Veja Gold Original (detergente)"},
    /* 868 */ {"Fishwife Mutant (TimeSplitters)", "Faixa de festa junina (bandeirola)"},
    /* 869 */ {"Fichup (Gogo's Crazy Bones)", "Ficha de poker (ficha, poker chip)"},
    /* 870 */ {"Foxy (FNAF)", "Focaccia"},
    /* 871 */ {"Victoria Cindry (One Piece)", "Avocado (abacate)"},
    /* 872 */ {"Uvogin (Hunter x Hunter)", "Vagoneta"},
    /* 873 */ {"Eve Wakamiya (BanG Dream!)", "Vacuum cleaner (aspirador, inglês)"},
    /* 874 */ {"Fukurokuju (One Piece)", "Fogo de artifício (rojão)"},
    /* 875 */ {"Vagalume (DC Comics)", "Vogue Eyelash curler (curvex, inglês)"},
    /* 876 */ {"Vagash (World of Warcraft)", "Vogue jewelled cuff (pulseira)"},
    /* 877 */ {"Fake Coco (Crash Bandicoot)", "Vogue compact mirror (compact mirror, inglês)"},
    /* 878 */ {"Fogo-fátuo (Ben 10)", "Fake fag (cigarro, inglês)"},
    /* 879 */ {"Vegapunk (One Piece)", "Fio de cabelo"},
    /* 880 */ {"Fives (Star Wars)", "Vuvuzela (buzina)"},
    /* 881 */ {"Fafa the Groundhog (Glove and Boots)", "Vivo Telefônica"},
    /* 882 */ {"Fei Fong (Xenogears)", "Vivian Chiu Turning It All Around"},
    /* 883 */ {"Vavoom (Felix the Cat)", "Favo de mel (favo)"},
    /* 884 */ {"Vivi Ornitier (Final Fantasy)", "Uva verde"},
    /* 885 */ {"Vivo Lorenzo (Vivo Movie)", "Fivela (cinto)"},
    /* 886 */ {"Vovó Juju (Irmão do Jorel)", "FIFISH Underwater Drones (drone)"},
    /* 887 */ {"Fivok (Crazy Bones)", "Vivi Calissendorff unique stoneware wall hanging sculpture"},
    /* 888 */ {"Fee-Fi-Fo-Fum (Disney)", "Viviovo D'oro (Erbium oxide, LED, radiômetro)"},
    /* 889 */ {"Vivi Bubble Tea (Mascot of Vivi Bubble Tea)", "Vive pro controller"},
    /* 890 */ {"Fabio Sparklemane (Fortnite)", "Ovo de páscoa"},
    /* 891 */ {"Faputa (Made in Abyss)", "Fabita Ordine"},
    /* 892 */ {"Fabian (The Flintstones)", "Fabian Gatermann's Mood poem"},
    /* 893 */ {"Fabio Medina (Marvel)", "F bomb (bomba)"},
    /* 894 */ {"Víbora (Kung Fu Panda)", "Vaporizador de cabelo (secador)"},
    /* 895 */ {"Fábio Lanzonelli (World of Warcraft)", "V belt pulley"},
    /* 896 */ {"Fupo-Chan (refsheet)", "Foppish wig (peruca de juiz)"},
    /* 897 */ {"Fubuki (One-Punch Man)", "V-packing"},
    /* 898 */ {"Fabio Fabuloso (Doc McStuffins)", "V-puff stitch (crochet, inglês)"},
    /* 899 */ {"Phoebe Buffay (Funko Pop!)", "Avião de papel"},
    /* 900 */ {"Busuzima (Bloody Roar)", "Passas (uva passa, raisin)"},
    /* 901 */ {"Besta (Ben 10)", "Obsidiana (minecraft)"},
    /* 902 */ {"Poison (Final Fight)", "Peça íntima (lingerie)"},
    /* 903 */ {"Bismarck (One Piece)", "Bosom wearables (inglês)"},
    /* 904 */ {"Bowser (Mario)", "Poço artesiano (poço)"},
    /* 905 */ {"Buzz Lightyear (Toy Story)", "Pão de sal"},
    /* 906 */ {"Bes Jordan (Space Runaway Ideon)", "Passagem (ticket)"},
    /* 907 */ {"Biscoito (Shrek)", "Bazuca"},
    /* 908 */ {"Pacifista (One Piece)", "Pacificador (capacete)"},
    /* 909 */ {"Buzby (TV Comic)", "Passaporte (visto)"},
    /* 910 */ {"Boots (Dora the Explorer)", "Pizza"},
    /* 911 */ {"Pateta (Disney)", "Batedor de claras (fuê, whisk)"},
    /* 912 */ {"Patinhas (Tio Patinhas)", "Patinho amarelo de banheira"},
    /* 913 */ {"Batman (DC Comics)", "Batom"},
    /* 914 */ {"Patrick (Bob Esponja)", "Batarang"},
    /* 915 */ {"Patolino (O Show dos Looney Tunes)", "Pedal"},
    /* 916 */ {"Obito Uchiha (Naruto)", "Potash (pedra, inglês)"},
    /* 917 */ {"Butt Guy (Scissor Seven)", "Buttock (bunda, nádegas)"},
    /* 918 */ {"Pathfinder (Apex Legends)", "Batavia's Eternal Flame"},
    /* 919 */ {"Betty Boop (Betty Boop)", "Potpie (torta, empada, inglês)"},
    /* 920 */ {"Benson (Apenas um Show)", "Pênis (condom training model)"},
    /* 921 */ {"Bender (Futurama)", "Piñata"},
    /* 922 */ {"Pinan (Champion Joe)", "Banana"},
    /* 923 */ {"Ipponmatsu (One Piece)", "Panam Panamá by Léa Baert"},
    /* 924 */ {"Bonnie Rockwaller (Kim Possible)", "Peneira"},
    /* 925 */ {"Bonolenov (hunter x hunter)", "Panel saw"},
    /* 926 */ {"Benjamin (pequena sereia)", "Punching bag (joão bobo, junior punching bag, inglês)"},
    /* 927 */ {"Bing Bong (Divertida Mente)", "Banqueta"},
    /* 928 */ {"Buena Festa (One Piece)", "Bóia inflável"},
    /* 929 */ {"Pen Pen (Neon Genesis Evangelion)", "Pen pot"},
    /* 930 */ {"Pumice (Marvel)", "Booms containment (inglês)"},
    /* 931 */ {"Bumi The Dream Walker (Coal Dog)", "Pomada"},
    /* 932 */ {"Paimon (Helluva Boss)", "Pimentão"},
    /* 933 */ {"Pemomarch (Final evolution of Pemo - Moco Moco Friends)", "Boom mic (microfone, lapela, inglês)"},
    /* 934 */ {"Boomer (Spyro)", "Bumerangue"},
    /* 935 */ {"Pummel (My Singing Monsters)", "Pé de moleque"},
    /* 936 */ {"Bum-Ju (Avatar)", "Beam shutter"},
    /* 937 */ {"Baymax (Operação Big Hero)", "Bamako Peace Monument"},
    /* 938 */ {"Bamf (Kitty Pryde's fairytale)", "Beam fruit press (Cross beam fruit press, inglês)"},
    /* 939 */ {"Pim Pimling (Smiling Friends)", "Bambu (cana de açúcar)"},
    /* 940 */ {"Apros (DC Comics)", "Berço"},
    /* 941 */ {"Birdo (Nintendo)", "Britadeira"},
    /* 942 */ {"Pernalonga (O Show dos Looney Tunes)", "Prancha (surfboard)"},
    /* 943 */ {"Behemoth (Disney)", "Berimbau"},
    /* 944 */ {"Perry o Ornitorrinco (Phineas e Ferb)", "Para-raios"},
    /* 945 */ {"Power Loader (Boku no Hero)", "Barril"},
    /* 946 */ {"Bruxa Lezah (O Show dos Looney Tunes)", "Barra de chocolate (chocolate)"},
    /* 947 */ {"Porquinho (Toy Story)", "Pergaminho"},
    /* 948 */ {"Prefeito (Mundo de Jack)", "Purflo nest"},
    /* 949 */ {"Puri-Puri Prisoner (One-Punch Man)", "Barbeador"},
    /* 950 */ {"Bill Azêdo (Detona Ralph)", "Bola de espelhos (disco ball)"},
    /* 951 */ {"Pluto (Disney)", "Pallet"},
    /* 952 */ {"Plankton (Bob Esponja)", "Balança justiça"},
    /* 953 */ {"Bloom (Clube das Winx)", "Plumbus (Rick and Morty)"},
    /* 954 */ {"Pilar (Cyberpunk: Edgerunners)", "Balão de ar quente"},
    /* 955 */ {"Billy Lee (Xenogears)", "Pilha alcalina (pilha, battery, alcalina pilha)"},
    /* 956 */ {"Bolshoi (DC comics)", "ball & chain (Luoem Bola, leg iron)"},
    /* 957 */ {"Pleakley (Lilo & Stitch)", "Bola de gude"},
    /* 958 */ {"Pilaf (dragon ball)", "Bola de futebol (bola)"},
    /* 959 */ {"Bulbassauro (Pokémon)", "Bola de boliche"},
    /* 960 */ {"Paige Sinclair (BoJack Horseman)", "Pouches (carteira)"},
    /* 961 */ {"Pochita (Chainsaw Man)", "Peão de xadrez"},
    /* 962 */ {"Passionlip (Fate/Grand Order)", "Beijinho"},
    /* 963 */ {"Bishamon (Night Warriors)", "Pijama"},
    /* 964 */ {"Bushranger (Fortnite)", "Abajour"},
    /* 965 */ {"Bushel (My Little Pony)", "Bushel (washtub, cesta, inglês)"},
    /* 966 */ {"Eboshi Shuuichi (Megaman)", "Bajaji (three-passenger tricycle)"},
    /* 967 */ {"BoJack (BoJack Horseman)", "Bexiga (balão)"},
    /* 968 */ {"Paige Overton (Starfield)", "Bucha vegetal (loofah)"},
    /* 969 */ {"PJ Berri (PaRappa the Rapper)", "Bucha para parede"},
    /* 970 */ {"Pixie-Bob (Boku no Hero)", "Abacus (ábaco, inglês)"},
    /* 971 */ {"Pact (Alchemy Stars)", "Bigode"},
    /* 972 */ {"Pequeno mal (pequena sereia)", "Bacon"},
    /* 973 */ {"Pac-Man (Pac-Man)", "Pokémon (pokebola)"},
    /* 974 */ {"Beaker (muppets)", "Bigorna"},
    /* 975 */ {"Piccolo (Dragon Ball)", "Pé de galinha"},
    /* 976 */ {"Pikachu (Pokémon)", "Pão de queijo"},
    /* 977 */ {"Pig God (One-Punch Man)", "Peacock (pena, pluma, inglês)"},
    /* 978 */ {"Big Feet (The Tom and Jerry)", "Buquê de flores"},
    /* 979 */ {"Pica-Pau (Pica-Pau)", "Pé de cabra"},
    /* 980 */ {"Beavis (Beavis and Butt-Head)", "Buffs (cross buffs)"},
    /* 981 */ {"Bafo de Onça (Disney)", "Bufeteira (chapa bufeteira)"},
    /* 982 */ {"Buffoon (Glitter Force)", "Buffon (jack-in-the-box toy, inglês)"},
    /* 983 */ {"Pavam Cr (Urban Rivals)", "Beef mix (carne moída)"},
    /* 984 */ {"Bova Ayrshire (Marvel)", "Bifurcador"},
    /* 985 */ {"Buffalo (One Piece)", "Bevel gauge (faca, canivete, faca lugubre, inglês)"},
    /* 986 */ {"Peevish (The Darkness)", "Puff cheeto (cheeto puff, inglês)"},
    /* 987 */ {"Bivouac (Screechers Wild)", "Bivaque (tenda)"},
    /* 988 */ {"Poof Fairywinkle-Cosma (Padrinhos mágicos)", "Puff vest (colete)"},
    /* 989 */ {"Beef Boss (Fortnite)", "Puff Puff pó facial"},
    /* 990 */ {"Bob Esponja (Bob Esponja)", "Bobsleigh's sled"},
    /* 991 */ {"Babidi (dragon ball)", "Babador"},
    /* 992 */ {"Papai Noel (A Origem dos Guardiões)", "Pepino"},
    /* 993 */ {"Pipo Monkey (Ape Escape)", "Pop whim (whim pop, picolé, paleta mexicana, inglês)"},
    /* 994 */ {"Piper (Robôs)", "Abóbora"},
    /* 995 */ {"Papa-Léguas (O Show dos Looney Tunes)", "Papel higiênico (higiênico)"},
    /* 996 */ {"Pipotchi (Ape Escape)", "Pop jelly (jelly pop)"},
    /* 997 */ {"Pappag (One Piece)", "Pipoca"},
    /* 998 */ {"Pop Fizz (Spyro)", "Pop filter de esponja"},
    /* 999 */ {"Peppa Pig (A Porquinha Peppa)", "Pip-Boy (Fallout)"}
};

#endif  // WORDLIST_HPP
